In [1]:
import numpy as np
from  PMED_instance import PMED_instance

In [2]:
instance = PMED_instance(r'C:\Users\Felipe\Projetos\Metaheuristicas\instances_alpha_neighbor_vns\or-library\pmed1.txt')

In [3]:
print(len(instance.dist))

100


In [4]:
print(instance.dist)

[[  0  30  76 ... 108  77  88]
 [ 30   0  46 ... 126  95 118]
 [ 76  46   0 ...  80  49  98]
 ...
 [108 126  80 ...   0  31  80]
 [ 77  95  49 ...  31   0  49]
 [ 88 118  98 ...  80  49   0]]
